------------------------------------------------------------------------------------------
                                    -- DATA MODELING
------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------
                            -- [1] Database and Schema Creation:
------------------------------------------------------------------------------------------

-- Create Database

CREATE DATABASE IF NOT EXISTS ECOM;

-- Use the ECOM Database

USE DATABASE ECOM;

-- Create All  7 Schemas of ECOM Database

CREATE SCHEMA IF NOT EXISTS ECOM.PRODUCT_SCHEMA
COMMENT = 'THIS IS PRODUCT_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO PRODUCT';

CREATE SCHEMA IF NOT EXISTS ECOM.CUSTOMER_SCHEMA
COMMENT = 'THIS IS CUSTOMER_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO CUSTOMER';

CREATE SCHEMA IF NOT EXISTS ECOM.ORDER_SCHEMA
COMMENT = 'THIS IS PRODUCT_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO PRODUCT';

CREATE SCHEMA IF NOT EXISTS ECOM.ORDER_ITEM_SCHEMA
COMMENT = 'THIS IS ORDER_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO ORDER';

CREATE SCHEMA IF NOT EXISTS ECOM.PAYMENT_SCHEMA
COMMENT = 'THIS IS PAYMENT_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO PAYMENT';

CREATE SCHEMA IF NOT EXISTS ECOM.SHIPPING_SCHEMA
COMMENT = 'THIS IS SHIPPING_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO SHIPPING';

CREATE SCHEMA IF NOT EXISTS ECOM.REVIEW_SCHEMA
COMMENT = 'THIS IS REVIEW_SCHEMA SCHEMA THAT STORE INFORMATION RELATED TO REVIEW';

---------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------
                            -- [2] Tables Creation in Each Schema:
------------------------------------------------------------------------------------------

-- [2.1] PRODUCTS Table Creation

CREATE OR REPLACE TABLE ECOM.PRODUCT_SCHEMA.PRODUCTS (
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE FLOAT,
    DESCRIPTION STRING,
    STOCK INT,
    BRAND STRING
);


-- [2.2] CUSTOMERS Table Creation

CREATE OR REPLACE TABLE ECOM.CUSTOMER_SCHEMA.CUSTOMERS (
    CUSTOMER_ID STRING PRIMARY KEY,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING UNIQUE,
    PHONE STRING,
    ADDRESS STRING,
    REGISTRATION_DATE TIMESTAMP
);


-- [2.3] ORDERS Table Creation

CREATE OR REPLACE TABLE ECOM.ORDER_SCHEMA.ORDERS (
    ORDER_ID STRING PRIMARY KEY,
    CUSTOMER_ID STRING REFERENCES ECOM.CUSTOMER_SCHEMA.CUSTOMERS(CUSTOMER_ID),
    ORDER_DATE TIMESTAMP,
    STATUS STRING,
    TOTAL_AMOUNT FLOAT,
    PAYMENT_METHOD STRING,
    SHIPPING_ADDRESS STRING
);


-- [2.4] ORDER_ITEMS Table Creation

CREATE OR REPLACE TABLE ECOM.ORDER_ITEM_SCHEMA.ORDER_ITEMS (
    ORDER_ITEM_ID STRING PRIMARY KEY,
    ORDER_ID STRING REFERENCES ECOM.ORDER_SCHEMA.ORDERS(ORDER_ID),
    PRODUCT_ID STRING REFERENCES ECOM.PRODUCT_SCHEMA.PRODUCTS(PRODUCT_ID),
    QUANTITY INT,
    PRICE FLOAT,
    TOTAL_AMOUNT FLOAT
);


-- [2.5] PAYMENTS Table Creation

CREATE OR REPLACE TABLE ECOM.PAYMENT_SCHEMA.PAYMENTS (
    PAYMENT_ID STRING PRIMARY KEY,
    ORDER_ID STRING REFERENCES ECOM.ORDER_SCHEMA.ORDERS(ORDER_ID),
    PAYMENT_DATE TIMESTAMP,
    PAYMENT_AMOUNT FLOAT,
    PAYMENT_STATUS STRING,
    PAYMENT_METHOD STRING
);


-- [2.6] SHIPPING Table Creation

CREATE OR REPLACE TABLE ECOM.SHIPPING_SCHEMA.SHIPPING (
    SHIPPING_ID STRING PRIMARY KEY,
    ORDER_ID STRING REFERENCES ECOM.ORDER_SCHEMA.ORDERS(ORDER_ID),
    SHIPPING_DATE TIMESTAMP,
    DELIVERY_DATE TIMESTAMP,
    CARRIER STRING,
    TRACKING_NUMBER STRING,
    SHIPPING_COST FLOAT
);

-- [2.7] REVIEWS Table Creation

CREATE OR REPLACE TABLE ECOM.REVIEW_SCHEMA.REVIEWS (
    REVIEW_ID STRING PRIMARY KEY,
    PRODUCT_ID STRING REFERENCES ECOM.PRODUCT_SCHEMA.PRODUCTS(PRODUCT_ID),
    CUSTOMER_ID STRING REFERENCES ECOM.CUSTOMER_SCHEMA.CUSTOMERS(CUSTOMER_ID),
    RATING INT,
    REVIEW_TEXT STRING,
    REVIEW_DATE TIMESTAMP,
    HELPFUL_VOTES INT
);
