------------------------------------------------------------------------------------------
                                    -- PIPELINE AUTOMATION
------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------
                -- [1] Create a Task to call all 7 Procedure for Data Loading:
------------------------------------------------------------------------------------------

-- [1.1] CREATE TASK FOR PRODUCTS PROCEDURE
CREATE OR REPLACE TASK ECOM.PRODUCT_SCHEMA.TASK_PRODUCTS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_PRODUCTS
    CALL ECOM.PRODUCT_SCHEMA.USP_LOAD_PRODUCTS();

    
-- [1.2] CREATE TASK FOR CUSTOMERS PROCEDURE
CREATE OR REPLACE TASK ECOM.CUSTOMER_SCHEMA.TASK_CUSTOMERS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_CUSTOMERS
    CALL ECOM.CUSTOMER_SCHEMA.USP_LOAD_CUSTOMERS();

    
-- [1.3] CREATE TASK FOR ORDERS PROCEDURE
CREATE OR REPLACE TASK ECOM.ORDER_SCHEMA.TASK_ORDERS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_ORDERS
    CALL ECOM.ORDER_SCHEMA.USP_LOAD_ORDERS();


-- [1.4] CREATE TASK FOR ORDER_ITEMS PROCEDURE
CREATE OR REPLACE TASK ECOM.ORDER_ITEM_SCHEMA.TASK_ORDER_ITEMS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_ORDER_ITEMS
    CALL ECOM.ORDER_ITEM_SCHEMA.USP_LOAD_ORDER_ITEMS();


-- [1.5] CREATE TASK FOR PAYMENTS PROCEDURE
CREATE OR REPLACE TASK ECOM.PAYMENT_SCHEMA.TASK_PAYMENTS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_PAYMENTS
    CALL ECOM.PAYMENT_SCHEMA.USP_LOAD_PAYMENTS();


-- [1.6] CREATE TASK FOR SHIPPING PROCEDURE
CREATE OR REPLACE TASK ECOM.SHIPPING_SCHEMA.TASK_SHIPPING
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_SHIPPING
    CALL ECOM.SHIPPING_SCHEMA.USP_LOAD_SHIPPING();


-- [1.7] CREATE TASK FOR REVIEWS PROCEDURE
CREATE OR REPLACE TASK ECOM.REVIEW_SCHEMA.TASK_REVIEWS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS
    -- Call the USP_LOAD_REVIEWS
    CALL ECOM.REVIEW_SCHEMA.USP_LOAD_REVIEWS();


-- CREATE A MAIN TASK FOR EXECUTE ALL THE TASKS    
CREATE OR REPLACE TASK ECOM.PUBLIC.TASK_ECOM_DATA_LOAD
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 38 16 * * * UTC'
AS
  BEGIN
    
    EXECUTE TASK ECOM.PRODUCT_SCHEMA.TASK_PRODUCTS;
    EXECUTE TASK ECOM.CUSTOMER_SCHEMA.TASK_CUSTOMERS;
    EXECUTE TASK ECOM.ORDER_SCHEMA.TASK_ORDERS;
    EXECUTE TASK ECOM.ORDER_ITEM_SCHEMA.TASK_ORDER_ITEMS;
    EXECUTE TASK ECOM.PAYMENT_SCHEMA.TASK_PAYMENTS;
    EXECUTE TASK ECOM.SHIPPING_SCHEMA.TASK_SHIPPING;
    EXECUTE TASK ECOM.REVIEW_SCHEMA.TASK_REVIEWS;

END;  

-- CHECK DATA IS PROPER LOAD OR NOT AFTER THAT YOU CAN RESUME THE TASK

ALTER TASK ECOM.PUBLIC.TASK_ECOM_DATA_LOAD SUSPEND;
ALTER TASK ECOM.PUBLIC.TASK_ECOM_DATA_LOAD RESUME;

-- IF YOU NEED THEN YOU CAN EXECUTE TASK MMANULLY

EXECUTE TASK ECOM.PUBLIC.TASK_ECOM_DATA_LOAD;